apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-fortune-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-fortune-mysql
  template:
    metadata:
      labels:
        app: java-fortune-mysql
    spec:
      containers:
        - name: java-fortune-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: fortune
            - name: MYSQL_USER
              value: tomcat
            - name: MYSQL_PASSWORD
              value: tomcat_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d/
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: mysql-init
          configMap:
            name: mysql-init-sql
        - name: mysql-config
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    init-connect='SET NAMES utf8mb4'

    [client]
    default-character-set=utf8mb4

    [mysql]
    default-character-set=utf8mb4
---
apiVersion: v1
kind: Service
metadata:
  name: java-fortune-mysql-service
spec:
  type: ClusterIP
  selector:
    app: java-fortune-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
